## Handling Imbalanced Dataset

##### 1. Up Sampling
##### 2. Down Sampling

In [ ]:
import numpy as np
import pandas as pd

#Set the random seed for reproducibility and this use if we code rerun then everytime it gives same random number as previous
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [ ]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET  
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1] * n_class_1
})

   feature_1  feature_2  target
0  -1.774224   0.285744       0
1  -1.201377   0.333279       0
2   1.096257   0.531807       0
3   0.861037  -0.354766       0
4  -1.520367  -1.120815       0

In [7]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [10]:
df.tail()
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## Upsampling

In [11]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [12]:
from sklearn.utils import resample
df_minority_upsample = resample(df_minority, replace=True, n_samples=len(df_majority), random_state=42)

In [13]:
df_minority_upsample.shape

(900, 3)

In [14]:
df_minority_upsample.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [15]:
df_upsampled = pd.concat([df_majority, df_minority_upsample])

In [16]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [22]:
df_majority = df[df['target'] == 0]
df_minority = df[df['target'] == 1]

In [23]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority, replace=False, n_samples=len(df_minority), random_state=42)

In [24]:
df_majority_downsampled.shape

(100, 3)

In [25]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [26]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64